### PR TITLE
fix(css): remove scrollbar

### PR DESCRIPTION
**Pull request by nithilan4**
Removed a useless scrollbar by reducing the entire container's bottom margin.

### CODE REVIEW

**Comment by nithilan4** [comment]
The extra padding below the ui fluid container creates a scrollbar that isn't necessary and screws with the github banner.
image

**Comment by jeromesimeon** [comment]
> The extra margin below the ui fluid container creates a scrollbar that isn't necessary and screws with the github banner.
> image

I'm not able to reproduce this (I've tried on Chrome and Safari). Could you please open an issue first?

**Comment by nithilan4** [comment]
#128

**Comment by nithilan4** [comment]
@jeromesimeon was there actually a use for that `font-family: Menlo` line? why was it there in the first place?

**Comment by jeromesimeon** [comment]
> @jeromesimeon was there actually a use for that `font-family: Menlo` line? why was it there in the first place?

A bit of investigation on this: `Menlo` is a nice monospace font but does not seem to be supported on Windows. The bug is actually that when not found, the CSS does not provide a proper alternative.

Removing it makes it look significantly less nice on MacOS, so it would be worth fixing by providing a windows friendly alternate (maybe along those lines: https://stackoverflow.com/questions/8187640/can-css-be-used-for-alternate-fonts)

**Comment by nithilan4** [comment]
oops, I thought that Menlo was just that serif font for some reason
i added monospace instead of Courier because Courier was a little too thin.

**Comment by jeromesimeon** [comment]
> oops, I thought that Menlo was just that serif font for some reason
> i added monospace instead of Courier because Courier was a little too thin.

I think that's great. It seems to work for me on the netlify preview. How about adding Consolas to that list, after Menlo? https://www.cssfontstack.com/Consolas

**Comment by nithilan4** [comment]
wow, consolas is far better than monospace. never knew it existed

**Pull request merged**
