### PR TITLE
DO NOT MERGE - Update to Cicero v0.11.x

### PR DESCRIPTION
**Pull request by dselman**
Signed-off-by: Dan Selman <danscode@selman.org>

### CODE REVIEW

**Comment by dselman** [comment]
@jeromesimeon strange failures here after updating versions: 
`[Error Executing Template] "Can't find variable: init"`
`System error. Unknown language: cicero`

**Comment by irmerk** [comment]
> Template studio is using the old ergo engine which is now completely gone. It has to be replaced by the new engine, which among other things requires to create an engine object (not static anymore). Most of the way execution is called in template studio is in Util.js.
> 
> @irmerk has seen that code so may be able to help.

If I understand what you're referring to, `Line 25` in `template-studio/src/TemplateStudio/Utils.js` should be changed from 
```
import Ergo from '@accordproject/ergo-compiler/lib/ergo.js';
```
to
```
import Ergo from '@accordproject/ergo-compiler/lib/compiler.js';
```

**Comment by jeromesimeon** [comment]
@irmerk

Not quite. You will need to use the new “Engine” class should be instantiated with e.g. const engine = new Engine(‘cicero’) and call engine.something(...). Also you should be able to get the logic from the template structure now.

This might be a not so trivial refactor.

**Comment by jeromesimeon** [comment]
Closing this PR, moving to a new branch caught up with master.

**Pull request closed without merging**
